FROM python:3.10-slim

WORKDIR /streamlit_V2

# Copie tous les fichiers 
COPY . .

# Met à jour pip et installe les dépendances
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose le port de Streamlit (8501 par défaut)
EXPOSE 8501

CMD ["streamlit", "run", "interface_v2.py", "--server.port=8501", "--server.address=0.0.0.0"]