channels:
- conda-forge
dependencies:
- python=3.10.16
- pip<=25.0
- pip:
  - mlflow==2.22.0
  - imbalanced-learn==0.13.0
  - numpy==2.2.5
  - pandas==2.2.3
  - psutil==7.0.0
  - pytest==8.3.5
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
